## Question 1: Creating a NumPy Array  
Write a Python code snippet to create a NumPy array of 10 zeros.

### Example:
- **Output:**  
  `array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])`


In [12]:
# Write your code here
import numpy as np
l=np.zeros(10)
print(l)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]




## Question 2: Creating a Range of Numbers  
Write a Python code snippet to create a NumPy array with numbers from 10 to 20 (inclusive) with a step of 2.

### Example:
- **Output:**  
  `array([10, 12, 14, 16, 18, 20])`

In [13]:
# Write your code here
l=np.arange(10,21,2)
print(l)

[10 12 14 16 18 20]


## Question 3: Reshaping an Array  
Write a Python code snippet to reshape a NumPy array with 12 elements into a 3x4 matrix.

### Example:
- **Input:**  
  `array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])`
  
- **Output:**  
  `array([[ 1,  2,  3,  4],  
         [ 5,  6,  7,  8],  
         [ 9, 10, 11, 12]])`

In [20]:
# Write your code here
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Question 4: Array Indexing  
Write a Python code snippet to retrieve the element at the 2nd row and 3rd column from a 3x4 matrix.

### Example:
- **Input:**  
  `array([[1, 2, 3, 4],  
         [5, 6, 7, 8],  
         [9, 10, 11, 12]])`
  
- **Output:**  
  `11`

In [24]:
# Write your code here
a=np.array([[1, 2, 3, 4],      [5, 6, 7, 8],      [9, 10, 11, 12]])
print(a[2][2])

11



## Question 5: Array Operations  
Write a Python code snippet to add 5 to every element of the following NumPy array.

### Example:
- **Input:**  
  `array([1, 2, 3, 4, 5])`
  
- **Output:**  
  `array([6, 7, 8, 9, 10])`

In [25]:
# Write your code here
a=np.array([1, 2, 3, 4, 5])
print(a+5)

[ 6  7  8  9 10]


## Question 6: Array Transposition  
Write a Python code snippet to transpose a 2x3 NumPy array.

### Example:
- **Input:**  
  `array([[1, 2, 3],  
         [4, 5, 6]])`
  
- **Output:**  
  `array([[1, 4],  
         [2, 5],  
         [3, 6]])`

In [33]:
# Write your code here
a=np.array([[1, 2, 3],      [4, 5, 6]])
an=a.reshape(3,2)
print(a.transpose(1,0))

[[1 4]
 [2 5]
 [3 6]]



## Question 7: Array Arithmetic  
Write a Python code snippet to multiply two NumPy arrays element-wise.

### Example:
- **Input:**  
  `array([1, 2, 3])`,  
  `array([4, 5, 6])`
  
- **Output:**  
  `array([4, 10, 18])`

In [35]:
# Write your code here
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
print(a*b)

[ 4 10 18]



## Question 9: Statistical Functions  
Write a Python code snippet to compute the mean of a NumPy array.

### Example:
- **Input:**  
  `array([10, 20, 30, 40, 50])`
  
- **Output:**  
  `30.0`

In [42]:
# Write your code here
a=np.array([10, 20, 30, 40, 50])
print(np.mean(a))

30.0


## Question 8: Boolean Indexing  
Write a Python code snippet to create a new NumPy array by selecting elements greater than 5 from the following array.

### Example:
- **Input:**  
  `array([1, 2, 3, 6, 7, 8])`
  
- **Output:**  
  `array([6, 7, 8])`

In [45]:
# Write your code here
a=np.array([1, 2, 3, 6, 7, 8])
print(a[a>5])

[6 7 8]


## Question 10: Stacking Arrays  
Write a Python code snippet to stack two NumPy arrays vertically.

### Example:
- **Input:**  
  `array([1, 2, 3])`,  
  `array([4, 5, 6])`
  
- **Output:**  
  `array([[1, 2, 3],  
         [4, 5, 6]])`


In [57]:
# Write your code here
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


## Question 11: Creating an Identity Matrix  
Write a Python code snippet to create a 3x3 identity matrix using NumPy.

### Example:
- **Output:**  
  `array([[1., 0., 0.],  
         [0., 1., 0.],  
         [0., 0., 1.]])`


In [58]:
# Write your code here
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Question 12: Array Dot Product  
Write a Python code snippet to compute the dot product of two NumPy arrays.

### Example:
- **Input:**  
  `array([1, 2])`,  
  `array([3, 4])`
  
- **Output:**  
  `11`

In [60]:
# Write your code here
a=np.array([1, 2])
b=np.array([3, 4])

print(np.dot(a,b))

11


## Question 13: Creating a Random Array  
Write a Python code snippet to create a NumPy array of 5 random numbers between 0 and 1.



In [62]:
# Write your code here
a=np.random.rand(1,5)
print(a)

[[0.38154213 0.94791189 0.03374079 0.83915047 0.84188425]]


## Question 14: Array Sorting  
Write a Python code snippet to sort a NumPy array in ascending order.

### Example:
- **Input:**  
  `array([3, 1, 4, 1, 5, 9, 2])`
  
- **Output:**  
  `array([1, 1, 2, 3, 4, 5, 9])`

In [69]:
# Write your code here
a=np.array([3, 1, 4, 1, 5, 9, 2])

print(np.sort(a))

[1 1 2 3 4 5 9]


## Question 15: Array Broadcasting  
Write a Python code snippet to add a 1D array to a 2D array using broadcasting.

### Example:
- **Input:**  
  `array([[1, 2],  
         [3, 4]])`,  
  `array([10, 20])`
  
- **Output:**  
  `array([[11, 22],  
         [13, 24]])`


In [70]:
# Write your code here
a=np.array([[1, 2],[3, 4]])
b=np.array([10, 20])

print(a+b)

[[11 22]
 [13 24]]



## Question 16: Reshaping with `-1`  
Write a Python code snippet to reshape a NumPy array with 9 elements into a 3x3 matrix using `-1` for automatic dimension calculation.

### Example:
- **Input:**  
  `array([1, 2, 3, 4, 5, 6, 7, 8, 9])`
  
- **Output:**  
  `array([[1, 2, 3],  
         [4, 5, 6],  
         [7, 8, 9]])`

In [72]:
# Write your code here
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(a.reshape(3,-1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Question 17: Element-wise Square  
Write a Python code snippet to square each element in a NumPy array.

### Example:
- **Input:**  
  `array([1, 2, 3, 4])`
  
- **Output:**  
  `array([1, 4, 9, 16])`


In [73]:
# Write your code here
a=np.array([1, 2, 3, 4])
print(a**2)

[ 1  4  9 16]


## Question 18: Counting Elements  
Write a Python code snippet to count the occurrences of a particular element (e.g., 3) in a NumPy array.

### Example:
- **Input:**  
  `array([1, 2, 3, 3, 4, 3])`
  
- **Output:**  
  `3`

In [78]:
# Write your code here
a=np.array([1, 2, 3, 3, 4, 3])
print(np.count_nonzero(a==3))

3
